2023-10-04/18:42:13		Starting in create_doc_embeddings method in data_parsing file......
2023-10-04/18:42:13		Starting in document_chunks method in data_parsing file......
2023-10-04/18:42:13		Error in document_chunks in data_parsing file : FileDataError('cannot open broken document')
2023-10-04/18:42:13		Error in create_doc_embeddings method in data_parsing file: TypeError("'NoneType' object is not iterable") 
2023-10-04/18:40:03		Starting in create_doc_embeddings method in data_parsing file......
2023-10-04/18:40:03		Starting in document_chunks method in data_parsing file......
2023-10-04/18:40:07		Error in create_doc_embeddings method in data_parsing file: APIConnectionError(message="Error communicating with OpenAI: HTTPSConnectionPool(host='perf-dsmbrsvc.anthem.com', port=443): Max retries exceeded with url: /llmgateway/openai/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000016E18C7E550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))", http_status=None, request_id=None) 
2023-10-04/18:42:13		Starting in extract_data method in structured_file_extraction file......
2023-10-04/18:42:13		Starting in _extract_contents method in structured_file_extraction file......
2023-10-04/18:42:13		Succsessfully executed in _extract_contents method in structured_file_extraction file......
2023-10-04/18:42:13		Starting in extract_headings method in structured_file_extraction file......
2023-10-04/18:42:18		Succsessfully executed in extract_headings method in structured_file_extraction file......
2023-10-04/18:42:18		Succsessfully executed in extract_data method in structured_file_extraction file......
2023-10-04/18:42:13		Starting in create_doc_embeddings method in data_parsing file......
2023-10-04/18:42:13		Starting in document_chunks method in data_parsing file......
2023-10-04/18:42:18		Error in create_doc_embeddings method in data_parsing file: APIConnectionError(message="Error communicating with OpenAI: HTTPSConnectionPool(host='perf-dsmbrsvc.anthem.com', port=443): Max retries exceeded with url: /llmgateway/openai/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000016E1D0CC410>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))", http_status=None, request_id=None) 
2023-10-04/18:42:18		Starting in extract_data method in structured_file_extraction file......
2023-10-04/18:42:18		Starting in _extract_contents method in structured_file_extraction file......
2023-10-04/18:42:18		Succsessfully executed in _extract_contents method in structured_file_extraction file......
2023-10-04/18:42:18		Starting in extract_headings method in structured_file_extraction file......
2023-10-04/18:42:22		Succsessfully executed in extract_headings method in structured_file_extraction file......
2023-10-04/18:42:22		Succsessfully executed in extract_data method in structured_file_extraction file......
2023-10-04/18:47:06		Starting in get_completion_from_messages method in data_processing file......
2023-10-04/18:47:06		Starting in get_similar_docs method in data_processing file......
2023-10-04/18:47:08		Error in get_similar_docs method in data_processing file: ValueError('Collection Manager_Handbook not found') 
2023-10-04/18:47:08		Error occured in get_completion_from_messages method in data_processing file: TypeError('can only join an iterable') 
2023-10-04/18:49:45		Starting in get_completion_from_messages method in data_processing file......
2023-10-04/18:49:45		Starting in get_similar_docs method in data_processing file......
2023-10-04/18:49:48		Error in get_similar_docs method in data_processing file: ValueError('Collection Manager_Handbook not found') 
2023-10-04/18:49:48		Error occured in get_completion_from_messages method in data_processing file: TypeError('can only join an iterable') 
